//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by game.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_BITMAP3                     185
#define IDB_BOX                         186
#define IDB_BUTTON                      187
#define IDB_BITMAP4                     188
#define IDB_COIN1                       188
#define IDB_BITMAP5                     189
#define IDB_COIN2                       189
#define IDB_BITMAP6                     190
#define IDB_CORNER1                     190
#define IDB_BITMAP7                     191
#define IDB_CORNER2                     191
#define IDB_BITMAP8                     192
#define IDB_CORNER3                     192
#define IDB_BITMAP9                     193
#define IDB_CORNER4                     193
#define IDB_DOOR                        194
#define IDB_FLOOR1                      195
#define IDB_FLOOR2                      196
#define IDB_KEY                         197
#define IDB_POTION                      200
#define IDB_SLIME1                      201
#define IDB_SLIME2                      202
#define IDB_SLIME3                      203
#define IDB_TRAP1                       204
#define IDB_BITMAP21                    205
#define IDB_TRAP2                       205
#define IDB_BITMAP22                    206
#define IDB_WALL1                       206
#define IDB_BITMAP23                    207
#define IDB_WALL2                       207
#define IDB_BITMAP24                    208
#define IDB_WALL3                       208
#define IDB_BITMAP25                    209
#define IDB_WALL4                       209
#define IDB_BITMAP26                    210
#define IDB_WALL5                       210
#define IDB_BITMAP27                    211
#define IDB_WALL6                       211
#define IDB_BITMAP28                    212
#define IDB_WALL7                       212
#define IDB_BITMAP29                    213
#define IDB_WALL8                       213
#define IDB_BITMAP30                    214
#define IDB_WALL9                       214
#define IDB_BITMAP31                    215
#define IDB_WALL10                      215
#define IDB_BITMAP32                    216
#define IDB_WALL11                      216
#define IDB_BITMAP33                    217
#define IDB_WALL12                      217
#define IDB_BITMAP34                    218
#define IDB_WALL13                      218
#define IDB_BITMAP35                    219
#define IDB_WATER                       219
#define IDB_WALL14                      220
#define IDB_BITMAP10                    221
#define IDB_BLACK                       221
#define IDB_PLAYER_ALIVE_LEFT_1         222
#define IDB_PLAYER_ALIVE_LEFT_2         223
#define IDB_PLAYER_ALIVE_LEFT_3         224
#define IDB_PLAYER_ALIVE_LEFT_4         225
#define IDB_PLAYER_ALIVE_RIGHT_1        226
#define IDB_PLAYER_ALIVE_RIGHT_2        227
#define IDB_PLAYER_ALIVE_RIGHT_3        228
#define IDB_PLAYER_ALIVE_RIGHT_4        229
#define IDB_PLAYER_DEAD_LEFT            230
#define IDB_PLAYER_DEAD_RIGHT           231
#define IDB_PLAYER_STANDBY              232
#define IDI_ICON1                       257
#define IDI_ICON2                       258
#define IDB_BITMAP11                    259
#define IDB_BITMAP12                    260
#define IDB_L2                          261
#define IDB_L3                          262
#define IDB_L4                          263
#define IDB_L5                          264
#define IDB_L6                          265
#define IDB_L7                          266
#define IDB_L8                          267
#define IDB_L9                          268
#define IDB_L10                         269
#define IDB_BITMAP37                    270
#define IDB_BITMAP38                    271
#define IDB_BITMAP39                    272
#define IDB_BITMAP40                    273
#define IDB_LEVELS                      305
#define IDB_MAINMENU                    306
#define IDB_INTRO                       307
#define IDB_PLAYER_ALIVE_UP_1           308
#define IDB_PLAYER_ALIVE_UP_2           309
#define IDB_BTN_LEVELS                  311
#define IDB_BTN_PLAY                    312
#define IDB_NEWLOGO                     313
#define IDB_BANNER                      314
#define IDB_HINT1                       315
#define IDB_HINT2                       316
#define IDB_HINT3                       317
#define IDB_HINT4                       318
#define IDB_HINT5                       319
#define IDB_HINT6                       320
#define IDB_HINT7                       321
#define IDB_HINT8                       322
#define IDB_ENDING                      323
#define IDB_SOUND_OFF                   324
#define IDB_SOUND_ON                    325
#define IDB_FAIL                        326
#define IDB_PASS                        327
#define IDB_num0                        328
#define IDB_num1                        329
#define IDB_num2                        331
#define IDB_BITMAP13                    332
#define IDB_ABOUT                       333
#define IDB_PIPE1                       334
#define IDB_PIPE2                       335
#define IDB_PIPE3                       336
#define IDB_PIPE4                       337
#define IDB_PIPE5                       338
#define IDB_TORCH1                      339
#define IDB_TORCH2                      340
#define IDB_BITMAP36                    341
#define IDB_TORCH3                      341
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        342
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
